version: '3'
x-styra-env:
  &styra-env
  EOPA_LICENSE_KEY: ${EOPA_LICENSE_KEY}
  STYRA_DAS_TOKEN: ${STYRA_DAS_TOKEN}
  EOPA_STYRA_DAS_TOKEN: ${STYRA_DAS_TOKEN}
  STYRA_DAS_TENANT: ${STYRA_DAS_TENANT}
  STYRA_DAS_SYSTEM: ${STYRA_DAS_SYSTEM:-}
x-styra-image: &eopa-image ${EOPA_IMAGE:-ghcr.io/styrainc/enterprise-opa:latest}

services:
  opa-ci:
    image: *eopa-image
    ports:
      - "8181:8181"
    command:
      - run
      - --server
      - --addr=:8181
      - policies/rules/rules.rego
    working_dir: /work
    volumes:
      - .styra.yaml:/work/.styra.yaml
      - .styra:/work/.styra
      - ./policies/prod:/work/policies
    environment: *styra-env
    profiles:
      - ci

  opa-prod:
    image: *eopa-image
    ports:
      - "8181:8181"
    command:
      - run
      - --server
      - --addr=:8181
      - --config-file=/opa.json
    volumes:
      - ./env/prod/opa.json:/opa.json
    environment: *styra-env
    profiles:
      - prod

  svc:
    build: svc/
    ports:
      - "8080:8080"
    environment:
      OPA_HOST: http://opa-${ENV:-ci}:8181

  integration-tests:
    image: ghcr.io/orange-opensource/hurl:latest
    volumes:
      - ./test:/test
    command:
      - --test
      - --retry=10
      - --variable=host=http://svc:8080
      - --glob=/test/integration/**/*.hurl
      - --report-junit=test/report.xml
    profiles:
      - tools
