version: '3'
services:
  opa:
    image: ghcr.io/styrainc/enterprise-opa:latest
    ports:
      - "9191:9191"
      - "8181:8181"
    command:
      - run
      - --server
      - --addr=:8181
      - users:/data/data.json
      - /data/policy.rego
      # - --config-file=/opa.json
    volumes:
      - ./opa/:/data
    environment:
      EOPA_LICENSE_KEY: ${EOPA_LICENSE_KEY}
      STYRA_DAS_TOKEN: ${STYRA_DAS_TOKEN}
      STYRA_DAS_TENANT: ${STYRA_DAS_TENANT}
      STYRA_DAS_SYSTEM: ${STYRA_DAS_SYSTEM:-}
    profiles:
      - ci

  svc:
    build: svc/
    ports:
      - "8080:8080"

  integration-tests:
    image: ghcr.io/orange-opensource/hurl:latest
    volumes:
      - ./test:/test
    command:
      - --test
      - --retry=10
      - --variable=host=http://svc:8080
      - --glob=/test/integration/**/*.hurl
      - --report-junit=test/report.xml
    profiles:
      - tools
