version: '3'
services:
  opa:
    image: ghcr.io/styrainc/enterprise-opa:latest
    ports:
      - "9191:9191"
      - "8181:8181"
    command:
      - run
      - --server
      - --addr=:8181
      # - --config-file=/opa.json
    volumes:
      - ./opa-das.json:/opa.json
    environment:
      EOPA_LICENSE_KEY: ${EOPA_LICENSE_KEY}
      STYRA_DAS_TOKEN: ${STYRA_DAS_TOKEN}
      STYRA_DAS_TENANT: ${STYRA_DAS_TENANT}
      STYRA_DAS_SYSTEM: ${STYRA_DAS_SYSTEM:-}
  svc:
    build: svc/
    ports:
      - "8080:8080"
