version: '3'
services:
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    ports:
      - "9901:9901"
      - "51051:51051"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--component-log-level", "ext_authz:trace"]
  opa:
    image: openpolicyagent/opa:latest-envoy
    ports:
      - "9191:9191"
    command:
      - run
      - --server
      - --config-file=/opa.yaml
      - /policy.rego
    volumes:
      - ./policy.rego:/policy.rego
      - ./opa.yaml:/opa.yaml
    # environment:
    #   EOPA_LICENSE_KEY: ${EOPA_LICENSE_KEY}
  svc:
    build: svc
    ports:
      - "8080:80"
