name: CD

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-e2e:
    name: Test E2E
    runs-on: ubuntu-22.04
    environment: main
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup
        run: docker compose --profile prod up --quiet-pull --wait --wait-timeout 300
        env:
          ENV: prod
          EOPA_LICENSE_KEY: ${{ secrets.EOPA_LICENSE_KEY }}
          STYRA_DAS_SYSTEM: a6db6a9be8ab41c995277c89fa5b3eba # eopa-testing-sr
          STYRA_DAS_TOKEN: ${{ secrets.STYRA_DAS_TOKEN }}
          STYRA_DAS_TENANT: expo
      - name: test
        run: docker compose run --quiet-pull integration-tests
      - name: dump logs
        run: docker compose logs
        if: failure()
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: test/report.xml
