name: CI

on:
  workflow_dispatch: {}
  pull_request: {}

# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-e2e:
    name: Test E2E
    runs-on: ubuntu-22.04
    environment: ci
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: robinraju/release-downloader@v1.9
        with:
          repository: StyraInc/enterprise-opa
          latest: true
          fileName: eopa_Linux_x86_64 
      - name: prep eopa binary
        run: |
          mkdir bin
          mv eopa_Linux_x86_64 bin/eopa
          chmod +x bin/eopa
          echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: pull libraries from DAS
        run: |
          eopa pull --url=https://expo.styra.com
          chmod -R a+rx .styra
        env:
          EOPA_LICENSE_KEY: ${{ secrets.EOPA_LICENSE_KEY }}
          EOPA_STYRA_DAS_TOKEN: ${{ secrets.STYRA_DAS_TOKEN }}
          STYRA_DAS_TENANT: expo
      - name: setup
        run: docker compose --profile ci up --quiet-pull --wait --wait-timeout 300
        env:
          EOPA_LICENSE_KEY: ${{ secrets.EOPA_LICENSE_KEY }}
          STYRA_DAS_SYSTEM: af5120e033934478bd6dcbd8bfca0c84
          STYRA_DAS_TOKEN: ${{ secrets.STYRA_DAS_TOKEN }}
          STYRA_DAS_TENANT: expo
      - name: test
        run: docker compose run --quiet-pull integration-tests
      - name: dump logs
        run: docker compose --profile ci logs
        if: failure()
      - name: dump logs of eopa-ci
        run: docker compose --profile ci logs opa-ci
        if: failure()
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: test/report.xml
