name: CI

on:
  workflow_dispatch: {}
  pull_request: {}

# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# env:
#   GO_VERSION: 1.21
#   BB_VERSION: 1.3.186

jobs:
  test-e2e:
    name: Test E2E
    runs-on: ubuntu-22.04
    environment: ci
    steps:
      - uses: gacts/install-hurl@v1
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup
        run: docker compose up --wait --wait-timeout 300
      - name: test
        run: hurl --test --glob "test/integration/**/*.hurl" --report-junit report.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: report.xml
